//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempleAll
{
    using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web.Mvc;
    
    public partial class Activity
    {
        [HiddenInput(DisplayValue = false)]
        public int ActivityID { get; set; }

        [Required(ErrorMessage = "กรุณากรอกหัวข้อกิจกรรม")]
        public string Name { get; set; }

        [Required(ErrorMessage = "กรุณากรอกรายละเอียดกิจกรรม")]
        public string Description { get; set; }

        [Required(ErrorMessage = "กรุณาเลือกประเภทของกิจกรรม")]
        public string Type { get; set; }

    }
}
