//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempleAll
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    
    public partial class Contact
    {
        [HiddenInput(DisplayValue = false)]
        public int ContactID { get; set; }

        [Required(ErrorMessage = "กรุณากรอกชื่อวัด")]
        [Display(Name = "ชื่อวัด")]
        public string Name { get; set; }

        [Required(ErrorMessage = "กรุณากรอกที่อยู่")]
        [Display(Name = "ที่อยู่")]
        public string Address { get; set; }

        [Display(Name = "หมายเลขโทรศัพท์")]
        public Nullable<int> Mobile { get; set; }

        [Display(Name = "อีเมล์ (ถ้ามี)")]
        public string Email { get; set; }

        [Display(Name = "facebook link")]
        public string Facebook { get; set; }
    }
}
