//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempleAll
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    
    public partial class ContactTopic
    {
        [HiddenInput(DisplayValue = false)]
        public int ContactTopicID { get; set; }

        [Required(ErrorMessage = "กรุณากรอกชื่อ นามสกุล")]
        [Display(Name = "ชื่อ นามสกุล")]
        public string Name { get; set; }

        [Required(ErrorMessage = "กรุณากรอกเรื่องที่ต้องการติดต่อ")]
        [Display(Name = "เรื่องที่ต้องการติดต่อ")]
        public string TopicName { get; set; }

        [Required(ErrorMessage = "กรุณากรอกรายละเอียด")]
        [Display(Name = "รายละเอียด")]
        public string TopicDescription { get; set; }

        [Required(ErrorMessage = "กรุณากรอกหมายเลขโทรศัพท์")]
        [Display(Name = "หมายเลขโทรศัพท์")]
        public Nullable<int> Mobile { get; set; }

        [Display(Name = "อีเมล์ (ถ้ามี)")]
        public string Email { get; set; }
    }
}
