//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempleAll
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    using System.Web.Mvc;
    
    public partial class History
    {
        [HiddenInput(DisplayValue = false)]
        public int HistoryID { get; set; }

        [HiddenInput(DisplayValue = false)]
        public int ImageSize { get; set; }

        [HiddenInput(DisplayValue = false)]
        public string FileName { get; set; }

        [HiddenInput(DisplayValue = false)]
        public byte[] ImageData { get; set; }

        [Required(ErrorMessage = "กรุณากรอกประวัติ")]
        public string Description { get; set; }

        [Required(ErrorMessage="กรุณาเลือกรูปภาพ")]
        public HttpPostedFileBase File { get; set; }
    }
}
